uid: 6379
gid: 6379
user: redis
group: redis
redis_version: "6.2.2"
redis_file: "redis-{{redis_version}}.tar.gz"
redis_instances_per_host: 2
redis_base_port: 6379 # Base port number for Redis instances
redis_data_dir: "/data/redis/data/"
redis_log_dir: "/data/redis/log/"
redis_base_dir: "/usr/local/redis/"
redis_src_dir: "/usr/local/src/"
redis_directories:
  - "{{ redis_base_dir }}"
  - "{{ redis_data_dir }}"
  - "{{ redis_log_dir }}"
  - "{{ redis_src_dir }}redis-{{ redis_version }}"
  - "{{ redis_src_dir }}{{ redis_file }}"
redis_password: 123456

